import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { NextUiProvider } from "@/providers/next-ui"

import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 
        "bg-main text-gray-200  min-h-screen mx-auto relative overflow-x-hidden")}>
        <NextUiProvider>
        <ToastContainer />
          {children}
        </NextUiProvider>
        
        
        </body>
    </html>
  )
}
